version: "3.3"
services:
  db:
    image: mysql:5.7
    container_name: cse611_mysql
    volumes:
      - db_file:/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: zhong

  app:
    build: .
    restart: always
    container_name: cse611
    links:
      - db
    environment:
      WAIT_HOSTS: db:3306
      MYSQL_PASSWORD: changeme
    ports:
      - '80:8000'
volumes:
  db_file: {}
